version: '3.8'

services:
  test:
    build: ./tests
    depends_on:
      - database-api
    networks:
      - tradewise-net

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tradewise_user
      - MONGO_INITDB_ROOT_PASSWORD=xxxxxxxxxxxxxxxx
      - MONGO_DATABASE=tradewise
    networks:
      - tradewise-net
    volumes:
      - db-test:/data/db

  database-api:
    build: ./services/mongodb-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tradewise_user
      - MONGO_INITDB_ROOT_PASSWORD=xxxxxxxxxxxxxxxx
      - MONGO_DATABASE=tradewise
    networks:
      - tradewise-net
    depends_on:
      - mongodb

networks:
  tradewise-net:
    driver: bridge

volumes:
  db-test:
